import  { Pokemon } from './pokemon';

export const POKEMONS: Pokemon[] = [
  {
    "id": 1,
    "name": "Bulbizarre",
    "types": ["Plante", "Poison"],
    "hp": 45,
    "Attack": 49,
    "Defense": 49,
    "SpAttack": 65,
    "SpDefense": 65,
    "Vitesse": 45,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png"
  }, {
    "id": 2,
    "name": "Herbizarre",
    "types": ["Plante", "Poison"],
    "hp": 60,
    "Attack": 62,
    "Defense": 63,
    "SpAttack": 80,
    "SpDefense": 80,
    "Vitesse": 60,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/002.png"
  }, {
    "id": 3,
    "name": "Florizarre",
    "types": ["Plante", "Poison"],
    "hp": 80,
    "Attack": 82,
    "Defense": 83,
    "SpAttack": 100,
    "SpDefense": 100,
    "Vitesse": 80,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/003.png"
  }, {
    "id": 4,
    "name": "Salam\u00e8che",
    "types": ["Feu"],
    "hp": 39,
    "Attack": 52,
    "Defense": 43,
    "SpAttack": 60,
    "SpDefense": 50,
    "Vitesse": 65,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/004.png"
  }, {
    "id": 5,
    "name": "Reptincel",
    "types": ["Feu"],
    "hp": 58,
    "Attack": 64,
    "Defense": 58,
    "SpAttack": 80,
    "SpDefense": 65,
    "Vitesse": 80,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/005.png"
  }, {
    "id": 6,
    "name": "Dracaufeu",
    "types": ["Feu", "Vol"],
    "hp": 78,
    "Attack": 84,
    "Defense": 78,
    "SpAttack": 109,
    "SpDefense": 85,
    "Vitesse": 100,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/006.png"
  }, {
    "id": 7,
    "name": "Carapuce",
    "types": ["Eau"],
    "hp": 44,
    "Attack": 48,
    "Defense": 65,
    "SpAttack": 50,
    "SpDefense": 64,
    "Vitesse": 43,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/007.png"
  }, {
    "id": 8,
    "name": "Carabaffe",
    "types": ["Eau"],
    "hp": 59,
    "Attack": 63,
    "Defense": 80,
    "SpAttack": 65,
    "SpDefense": 80,
    "Vitesse": 58,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/008.png"
  }, {
    "id": 9,
    "name": "Tortank",
    "types": ["Eau"],
    "hp": 79,
    "Attack": 83,
    "Defense": 100,
    "SpAttack": 85,
    "SpDefense": 105,
    "Vitesse": 78,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/009.png"
  }, {
    "id": 10,
    "name": "Chenipan",
    "types": ["Insecte"],
    "hp": 45,
    "Attack": 30,
    "Defense": 35,
    "SpAttack": 20,
    "SpDefense": 20,
    "Vitesse": 45,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/010.png"
  }, {
    "id": 11,
    "name": "Chrysacier",
    "types": ["Insecte"],
    "hp": 50,
    "Attack": 20,
    "Defense": 55,
    "SpAttack": 25,
    "SpDefense": 25,
    "Vitesse": 30,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/011.png"
  }, {
    "id": 12,
    "name": "Papilusion",
    "types": ["Insecte", "Vol"],
    "hp": 60,
    "Attack": 45,
    "Defense": 50,
    "SpAttack": 90,
    "SpDefense": 80,
    "Vitesse": 70,

    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/012.png"
  }, {
    "id": 13,
    "name": "Aspicot",
    "types": ["Insecte", "Poison"],
    "hp": 40,
    "Attack": 35,
    "Defense": 30,
    "SpAttack": 20,
    "SpDefense": 20,
    "Vitesse": 50,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/013.png"
  }, {
    "id": 14,
    "name": "Coconfort",
    "types": ["Insecte", "Poison"],
    "hp": 45,
    "Attack": 25,
    "Defense": 50,
    "SpAttack": 25,
    "SpDefense": 25,
    "Vitesse": 35,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/014.png"
  }, {
    "id": 15,
    "name": "Dardargnan",
    "types": ["Insecte", "Poison"],
    "hp": 65,
    "Attack": 90,
    "Defense": 40,
    "SpAttack": 45,
    "SpDefense": 80,
    "Vitesse": 75,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/015.png"
  }, {
    "id": 16,
    "name": "Roucool",
    "types": ["Normal", "Vol"],
    "hp": 40,
    "Attack": 45,
    "Defense": 40,
    "SpAttack": 35,
    "SpDefense": 35,
    "Vitesse": 56,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/016.png"
  }, {
    "id": 17,
    "name": "Roucoups",
    "types": ["Normal", "Vol"],
    "hp": 63,
    "Attack": 60,
    "Defense": 55,
    "SpAttack": 50,
    "SpDefense": 50,
    "Vitesse": 71,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/017.png"
  }, {
    "id": 18,
    "name": "Roucarnage",
    "types": ["Normal", "Vol"],
    "hp": 83,
    "Attack": 80,
    "Defense": 75,
    "SpAttack": 70,
    "SpDefense": 70,
    "Vitesse": 101,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/018.png"
  }, {
    "id": 19,
    "name": "Rattata",
    "types": ["Normal"],
    "hp": 30,
    "Attack": 56,
    "Defense": 35,
    "SpAttack": 25,
    "SpDefense": 35,
    "Vitesse": 72,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/019.png"
  }, {
    "id": 20,
    "name": "Rattatac",
    "types": ["Normal"],
    "hp": 55,
    "Attack": 81,
    "Defense": 60,
    "SpAttack": 50,
    "SpDefense": 70,
    "Vitesse": 97,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/020.png"
  }, {
    "id": 21,
    "name": "Piafabec",
    "types": ["Normal", "Vol"],
    "hp": 40,
    "Attack": 60,
    "Defense": 30,
    "SpAttack": 31,
    "SpDefense": 31,
    "Vitesse": 70,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/021.png"
  }, {
    "id": 22,
    "name": "Rapasdepic",
    "types": ["Normal", "Vol"],
    "hp": 65,
    "Attack": 90,
    "Defense": 65,
    "SpAttack": 61,
    "SpDefense": 61,
    "Vitesse": 100,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/022.png"
  }, {
    "id": 23,
    "name": "Abo",
    "types": ["Poison"],
    "hp": 35,
    "Attack": 60,
    "Defense": 44,
    "SpAttack": 40,
    "SpDefense": 54,
    "Vitesse": 55,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/023.png"
  }, {
    "id": 24,
    "name": "Arbok",
    "types": ["Poison"],
    "hp": 60,
    "Attack": 95,
    "Defense": 69,
    "SpAttack": 65,
    "SpDefense": 79,
    "Vitesse": 80,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/024.png"
  }, {
    "id": 25,
    "name": "Pikachu",
    "types": ["Electrik"],
    "hp": 35,
    "Attack": 55,
    "Defense": 40,
    "SpAttack": 50,
    "SpDefense": 50,
    "Vitesse": 90,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/025.png"
  }, {
    "id": 26,
    "name": "Raichu",
    "types": ["Electrik"],
    "hp": 60,
    "Attack": 90,
    "Defense": 55,
    "SpAttack": 90,
    "SpDefense": 80,
    "Vitesse": 110,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/026.png"
  }, {
    "id": 27,
    "name": "Sabelette",
    "types": ["Combat"],
    "hp": 50,
    "Attack": 75,
    "Defense": 85,
    "SpAttack": 20,
    "SpDefense": 30,
    "Vitesse": 40,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/027.png"
  }, {
    "id": 28,
    "name": "Sablaireau",
    "types": ["Combat"],
    "hp": 75,
    "Attack": 100,
    "Defense": 110,
    "SpAttack": 45,
    "SpDefense": 55,
    "Vitesse": 65,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/028.png"
  }, {
    "id": 29,
    "name": "Nidoran\u2640",
    "types": ["Poison"],
    "hp": 55,
    "Attack": 47,
    "Defense": 52,
    "SpAttack": 40,
    "SpDefense": 40,
    "Vitesse": 41,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/029.png"
  }, {
    "id": 30,
    "name": "Nidorina",
    "types": ["Poison"],
    "hp": 70,
    "Attack": 62,
    "Defense": 67,
    "SpAttack": 55,
    "SpDefense": 55,
    "Vitesse": 56,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/030.png"
  }, {
    "id": 31,
    "name": "Nidoqueen",
    "types": ["Poison", "Combat"],
    "hp": 90,
    "Attack": 92,
    "Defense": 87,
    "SpAttack": 75,
    "SpDefense": 85,
    "Vitesse": 76,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/031.png"
  }, {
    "id": 32,
    "name": "Nidoran\u2642",
    "types": ["Poison"],
    "hp": 46,
    "Attack": 57,
    "Defense": 40,
    "SpAttack": 40,
    "SpDefense": 40,
    "Vitesse": 50,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/032.png"
  }, {
    "id": 33,
    "name": "Nidorino",
    "types": ["Poison"],
    "hp": 61,
    "Attack": 72,
    "Defense": 57,
    "SpAttack": 55,
    "SpDefense": 55,
    "Vitesse": 65,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/033.png"
  }, {
    "id": 34,
    "name": "Nidoking",
    "types": ["Poison", "Sol"],
    "hp": 81,
    "Attack": 102,
    "Defense": 77,
    "SpAttack": 85,
    "SpDefense": 75,
    "Vitesse": 85,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/034.png"
  }, {
    "id": 35,
    "name": "M\u00e9lof\u00e9e",
    "types": ["Fée"],
    "hp": 70,
    "Attack": 45,
    "Defense": 48,
    "SpAttack": 60,
    "SpDefense": 65,
    "Vitesse": 35,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/035.png"
  }, {
    "id": 36,
    "name": "M\u00e9lodelfe",
    "types": ["Fée"],
    "hp": 95,
    "Attack": 70,
    "Defense": 73,
    "SpAttack": 95,
    "SpDefense": 90,
    "Vitesse": 60,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/036.png"
  }, {
    "id": 37,
    "name": "Goupix",
    "types": ["Feu"],
    "hp": 38,
    "Attack": 41,
    "Defense": 40,
    "SpAttack": 50,
    "SpDefense": 65,
    "Vitesse": 65,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/037.png"
  }, {
    "id": 38,
    "name": "Feunard",
    "types": ["Feu"],
    "hp": 73,
    "Attack": 76,
    "Defense": 75,
    "SpAttack": 81,
    "SpDefense": 100,
    "Vitesse": 100,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/038.png"
  }, {
    "id": 39,
    "name": "Rondoudou",
    "types": ["Normal", "Fée"],
    "hp": 115,
    "Attack": 45,
    "Defense": 20,
    "SpAttack": 45,
    "SpDefense": 25,
    "Vitesse": 20,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/039.png"
  }, {
    "id": 40,
    "name": "Grodoudou",
    "types": ["Normal", "Fée"],
    "hp": 140,
    "Attack": 70,
    "Defense": 45,
    "SpAttack": 85,
    "SpDefense": 50,
    "Vitesse": 45,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/040.png"
  }, {
    "id": 41,
    "name": "Nosferapti",
    "types": ["Poison", "Vol"],
    "hp": 40,
    "Attack": 45,
    "Defense": 35,
    "SpAttack": 30,
    "SpDefense": 40,
    "Vitesse": 55,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/041.png"
  }, {
    "id": 42,
    "name": "Nosferalto",
    "types": ["Poison", "Vol"],
    "hp": 75,
    "Attack": 80,
    "Defense": 70,
    "SpAttack": 65,
    "SpDefense": 75,
    "Vitesse": 90,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/042.png"
  }, {
    "id": 43,
    "name": "Mystherbe",
    "types": ["Plante", "Poison"],
    "hp": 45,
    "Attack": 50,
    "Defense": 55,
    "SpAttack": 75,
    "SpDefense": 65,
    "Vitesse": 30,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/043.png"
  }, {
    "id": 44,
    "name": "Ortide",
    "types": ["Plante", "Poison"],
    "hp": 60,
    "Attack": 65,
    "Defense": 70,
    "SpAttack": 85,
    "SpDefense": 75,
    "Vitesse": 40,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/044.png"
  }, {
    "id": 45,
    "name": "Rafflesia",
    "types": ["Plante", "Poison"],
    "hp": 75,
    "Attack": 80,
    "Defense": 85,
    "SpAttack": 110,
    "SpDefense": 90,
    "Vitesse": 50,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/045.png"
  }, {
    "id": 46,
    "name": "Paras",
    "types": ["Insecte", "Plante"],
    "hp": 35,
    "Attack": 70,
    "Defense": 55,
    "SpAttack": 45,
    "SpDefense": 55,
    "Vitesse": 25,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/046.png"
  }, {
    "id": 47,
    "name": "Parasect",
    "types": ["Insecte", "Plante"],
    "hp": 60,
    "Attack": 95,
    "Defense": 80,
    "SpAttack": 60,
    "SpDefense": 80,
    "Vitesse": 30,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/047.png"
  }, {
    "id": 48,
    "name": "Mimitoss",
    "types": ["Insecte", "Poison"],
    "hp": 60,
    "Attack": 55,
    "Defense": 50,
    "SpAttack": 40,
    "SpDefense": 55,
    "Vitesse": 45,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/048.png"
  }, {
    "id": 49,
    "name": "A\u00e9romite",
    "types": ["Insecte", "Poison"],
    "hp": 70,
    "Attack": 65,
    "Defense": 60,
    "SpAttack": 90,
    "SpDefense": 75,
    "Vitesse": 90,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/049.png"
  }, {
    "id": 50,
    "name": "Taupiqueur",
    "types": ["Sol"],
    "hp": 10,
    "Attack": 55,
    "Defense": 25,
    "SpAttack": 35,
    "SpDefense": 45,
    "Vitesse": 95,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/050.png"
  }, {
    "id": 51,
    "name": "Triopikeur",
    "types": ["Sol"],
    "hp": 35,
    "Attack": 100,
    "Defense": 50,
    "SpAttack": 50,
    "SpDefense": 70,
    "Vitesse": 120,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/051.png"
  }, {
    "id": 52,
    "name": "Miaouss",
    "types": ["Normal"],
    "hp": 40,
    "Attack": 45,
    "Defense": 35,
    "SpAttack": 40,
    "SpDefense": 40,
    "Vitesse": 90,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/052.png"
  }, {
    "id": 53,
    "name": "Persian",
    "types": ["Normal"],
    "hp": 65,
    "Attack": 70,
    "Defense": 60,
    "SpAttack": 65,
    "SpDefense": 65,
    "Vitesse": 115,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/053.png"
  }, {
    "id": 54,
    "name": "Psykokwak",
    "types": ["Eau"],
    "hp": 50,
    "Attack": 52,
    "Defense": 48,
    "SpAttack": 65,
    "SpDefense": 50,
    "Vitesse": 55,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/054.png"
  }, {
    "id": 55,
    "name": "Akwakwak",
    "types": ["Eau"],
    "hp": 80,
    "Attack": 82,
    "Defense": 78,
    "SpAttack": 95,
    "SpDefense": 80,
    "Vitesse": 85,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/055.png"
  }, {
    "id": 56,
    "name": "F\u00e9rosinge",
    "types": ["Combat"],
    "hp": 40,
    "Attack": 80,
    "Defense": 35,
    "SpAttack": 35,
    "SpDefense": 45,
    "Vitesse": 70,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/056.png"
  }, {
    "id": 57,
    "name": "Colossinge",
    "types": ["Combat"],
    "hp": 65,
    "Attack": 105,
    "Defense": 60,
    "SpAttack": 60,
    "SpDefense": 70,
    "Vitesse": 95,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/057.png"
  }, {
    "id": 58,
    "name": "Caninos",
    "types": ["Feu"],
    "hp": 55,
    "Attack": 70,
    "Defense": 45,
    "SpAttack": 70,
    "SpDefense": 50,
    "Vitesse": 60,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/058.png"
  }, {
    "id": 59,
    "name": "Arcanin",
    "types": ["Feu"],
    "hp": 90,
    "Attack": 110,
    "Defense": 80,
    "SpAttack": 100,
    "SpDefense": 80,
    "Vitesse": 95,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/059.png"
  }, {
    "id": 60,
    "name": "Ptitard",
    "types": ["Eau"],
    "hp": 40,
    "Attack": 50,
    "Defense": 40,
    "SpAttack": 40,
    "SpDefense": 40,
    "Vitesse": 90,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/060.png"
  }, {
    "id": 61,
    "name": "T\u00eatarte",
    "types": ["Eau"],
    "hp": 65,
    "Attack": 65,
    "Defense": 65,
    "SpAttack": 50,
    "SpDefense": 50,
    "Vitesse": 90,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/061.png"
  }, {
    "id": 62,
    "name": "Tartard",
    "types": ["Eau", "Combat"],
    "hp": 90,
    "Attack": 95,
    "Defense": 95,
    "SpAttack": 70,
    "SpDefense": 90,
    "Vitesse": 70,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/062.png"
  }, {
    "id": 63,
    "name": "Abra",
    "types": ["Psy"],
    "hp": 25,
    "Attack": 20,
    "Defense": 15,
    "SpAttack": 105,
    "SpDefense": 55,
    "Vitesse": 90,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/063.png"
  }, {
    "id": 64,
    "name": "Kadabra",
    "types": ["Psy"],
    "hp": 40,
    "Attack": 35,
    "Defense": 30,
    "SpAttack": 120,
    "SpDefense": 70,
    "Vitesse": 105,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/064.png"
  }, {
    "id": 65,
    "name": "Alakazam",
    "types": ["Psy"],
    "hp": 55,
    "Attack": 50,
    "Defense": 45,
    "SpAttack": 135,
    "SpDefense": 95,
    "Vitesse": 120,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/065.png"
  }, {
    "id": 66,
    "name": "Machoc",
    "types": ["Combat"],
    "hp": 70,
    "Attack": 80,
    "Defense": 50,
    "SpAttack": 35,
    "SpDefense": 35,
    "Vitesse": 35,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/066.png"
  }, {
    "id": 67,
    "name": "Machopeur",
    "types": ["Combat"],
    "hp": 80,
    "Attack": 100,
    "Defense": 70,
    "SpAttack": 50,
    "SpDefense": 60,
    "Vitesse": 45,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/067.png"
  }, {
    "id": 68,
    "name": "Mackogneur",
    "types": ["Combat"],
    "hp": 90,
    "Attack": 130,
    "Defense": 80,
    "SpAttack": 65,
    "SpDefense": 85,
    "Vitesse": 55,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/068.png"
  }, {
    "id": 69,
    "name": "Ch\u00e9tiflor",
    "types": ["Plante", "Poison"],
    "hp": 50,
    "Attack": 75,
    "Defense": 35,
    "SpAttack": 70,
    "SpDefense": 30,
    "Vitesse": 40,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/069.png"
  }, {
    "id": 70,
    "name": "Boustiflor",
    "types": ["Plante", "Poison"],
    "hp": 65,
    "Attack": 90,
    "Defense": 50,
    "SpAttack": 85,
    "SpDefense": 45,
    "Vitesse": 55,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/070.png"
  }, {
    "id": 71,
    "name": "Empiflor",
    "types": ["Plante", "Poison"],
    "hp": 80,
    "Attack": 105,
    "Defense": 65,
    "SpAttack": 100,
    "SpDefense": 70,
    "Vitesse": 70,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/071.png"
  }, {
    "id": 72,
    "name": "Tentacool",
    "types": ["Eau", "Poison"],
    "hp": 40,
    "Attack": 40,
    "Defense": 35,
    "SpAttack": 50,
    "SpDefense": 100,
    "Vitesse": 70,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/072.png"
  }, {
    "id": 73,
    "name": "Tentacruel",
    "types": ["Eau", "Poison"],
    "hp": 80,
    "Attack": 70,
    "Defense": 65,
    "SpAttack": 80,
    "SpDefense": 120,
    "Vitesse": 100,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/073.png"
  }, {
    "id": 74,
    "name": "Racaillou",
    "types": ["Rock", "Sol"],
    "hp": 40,
    "Attack": 80,
    "Defense": 100,
    "SpAttack": 30,
    "SpDefense": 30,
    "Vitesse": 20,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/074.png"
  }, {
    "id": 75,
    "name": "Gravalanch",
    "types": ["Rock", "Sol"],
    "hp": 55,
    "Attack": 95,
    "Defense": 115,
    "SpAttack": 45,
    "SpDefense": 45,
    "Vitesse": 35,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/075.png"
  }, {
    "id": 76,
    "name": "Grolem",
    "types": ["Rock", "Sol"],
    "hp": 80,
    "Attack": 120,
    "Defense": 130,
    "SpAttack": 55,
    "SpDefense": 65,
    "Vitesse": 45,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/076.png"
  }, {
    "id": 77,
    "name": "Ponyta",
    "types": ["Feu"],
    "hp": 50,
    "Attack": 85,
    "Defense": 55,
    "SpAttack": 65,
    "SpDefense": 65,
    "Vitesse": 90,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/077.png"
  }, {
    "id": 78,
    "name": "Galopa",
    "types": ["Feu"],
    "hp": 65,
    "Attack": 100,
    "Defense": 70,
    "SpAttack": 80,
    "SpDefense": 80,
    "Vitesse": 105,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/078.png"
  }, {
    "id": 79,
    "name": "Ramoloss",
    "types": ["Eau", "Psy"],
    "hp": 90,
    "Attack": 65,
    "Defense": 65,
    "SpAttack": 40,
    "SpDefense": 40,
    "Vitesse": 15,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/079.png"
  }, {
    "id": 80,
    "name": "Flagadoss",
    "types": ["Eau", "Psy"],
    "hp": 95,
    "Attack": 75,
    "Defense": 110,
    "SpAttack": 100,
    "SpDefense": 80,
    "Vitesse": 30,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/080.png"
  }, {
    "id": 81,
    "name": "Magn\u00e9ti",
    "types": ["Electrik", "Steel"],
    "hp": 25,
    "Attack": 35,
    "Defense": 70,
    "SpAttack": 95,
    "SpDefense": 55,
    "Vitesse": 45,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/081.png"
  }, {
    "id": 82,
    "name": "Magn\u00e9ton",
    "types": ["Electrik", "Steel"],
    "hp": 50,
    "Attack": 60,
    "Defense": 95,
    "SpAttack": 120,
    "SpDefense": 70,
    "Vitesse": 70,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/082.png"
  }, {
    "id": 83,
    "name": "Canarticho",
    "types": ["Normal", "Vol"],
    "hp": 52,
    "Attack": 90,
    "Defense": 55,
    "SpAttack": 58,
    "SpDefense": 62,
    "Vitesse": 60,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/083.png"
  }, {
    "id": 84,
    "name": "Doduo",
    "types": ["Normal", "Vol"],
    "hp": 35,
    "Attack": 85,
    "Defense": 45,
    "SpAttack": 35,
    "SpDefense": 35,
    "Vitesse": 75,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/084.png"
  }, {
    "id": 85,
    "name": "Dodrio",
    "types": ["Normal", "Vol"],
    "hp": 60,
    "Attack": 110,
    "Defense": 70,
    "SpAttack": 60,
    "SpDefense": 60,
    "Vitesse": 110,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/085.png"
  }, {
    "id": 86,
    "name": "Otaria",
    "types": ["Eau"],
    "hp": 65,
    "Attack": 45,
    "Defense": 55,
    "SpAttack": 45,
    "SpDefense": 70,
    "Vitesse": 45,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/086.png"
  }, {
    "id": 87,
    "name": "Lamantine",
    "types": ["Eau", "Glace"],
    "hp": 90,
    "Attack": 70,
    "Defense": 80,
    "SpAttack": 70,
    "SpDefense": 95,
    "Vitesse": 70,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/087.png"
  }, {
    "id": 88,
    "name": "Tadmorv",
    "types": ["Poison"],
    "hp": 80,
    "Attack": 80,
    "Defense": 50,
    "SpAttack": 40,
    "SpDefense": 50,
    "Vitesse": 25,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/088.png"
  }, {
    "id": 89,
    "name": "Grotadmorv",
    "types": ["Poison"],
    "hp": 105,
    "Attack": 105,
    "Defense": 75,
    "SpAttack": 65,
    "SpDefense": 100,
    "Vitesse": 50,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/089.png"
  }, {
    "id": 90,
    "name": "Kokiyas",
    "types": ["Eau"],
    "hp": 30,
    "Attack": 65,
    "Defense": 100,
    "SpAttack": 45,
    "SpDefense": 25,
    "Vitesse": 40,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/090.png"
  }, {
    "id": 91,
    "name": "Crustabri",
    "types": ["Eau", "Glace"],
    "hp": 50,
    "Attack": 95,
    "Defense": 180,
    "SpAttack": 85,
    "SpDefense": 45,
    "Vitesse": 70,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/091.png"
  }, {
    "id": 92,
    "name": "Fantominus",
    "types": ["Ghost", "Poison"],
    "hp": 30,
    "Attack": 35,
    "Defense": 30,
    "SpAttack": 100,
    "SpDefense": 35,
    "Vitesse": 80,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/092.png"
  }, {
    "id": 93,
    "name": "Spectrum",
    "types": ["Ghost", "Poison"],
    "hp": 45,
    "Attack": 50,
    "Defense": 45,
    "SpAttack": 115,
    "SpDefense": 55,
    "Vitesse": 95,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/093.png"
  }, {
    "id": 94,
    "name": "Ectoplasma",
    "types": ["Ghost", "Poison"],
    "hp": 60,
    "Attack": 65,
    "Defense": 60,
    "SpAttack": 130,
    "SpDefense": 75,
    "Vitesse": 110,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/094.png"
  }, {
    "id": 95,
    "name": "Onix",
    "types": ["Rock", "Sol"],
    "hp": 35,
    "Attack": 45,
    "Defense": 160,
    "SpAttack": 30,
    "SpDefense": 45,
    "Vitesse": 70,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/095.png"
  }, {
    "id": 96,
    "name": "Soporifik",
    "types": ["Psy"],
    "hp": 60,
    "Attack": 48,
    "Defense": 45,
    "SpAttack": 43,
    "SpDefense": 90,
    "Vitesse": 42,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/096.png"
  }, {
    "id": 97,
    "name": "Hypnomade",
    "types": ["Psy"],
    "hp": 85,
    "Attack": 73,
    "Defense": 70,
    "SpAttack": 73,
    "SpDefense": 115,
    "Vitesse": 67,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/097.png"
  }, {
    "id": 98,
    "name": "Krabby",
    "types": ["Eau"],
    "hp": 30,
    "Attack": 105,
    "Defense": 90,
    "SpAttack": 25,
    "SpDefense": 25,
    "Vitesse": 50,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/098.png"
  }, {
    "id": 99,
    "name": "Krabboss",
    "types": ["Eau"],
    "hp": 55,
    "Attack": 130,
    "Defense": 115,
    "SpAttack": 50,
    "SpDefense": 50,
    "Vitesse": 75,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/099.png"
  }, {
    "id": 100,
    "name": "Voltorbe",
    "types": ["Electrik"],
    "hp": 40,
    "Attack": 30,
    "Defense": 50,
    "SpAttack": 55,
    "SpDefense": 55,
    "Vitesse": 100,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/100.png"
  }, {
    "id": 101,
    "name": "\u00c9lectrode",
    "types": ["Electrik"],
    "hp": 60,
    "Attack": 50,
    "Defense": 70,
    "SpAttack": 80,
    "SpDefense": 80,
    "Vitesse": 150,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/101.png"
  }, {
    "id": 102,
    "name": "Noeunoeuf",
    "types": ["Plante", "Psy"],
    "hp": 60,
    "Attack": 40,
    "Defense": 80,
    "SpAttack": 60,
    "SpDefense": 45,
    "Vitesse": 40,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/102.png"
  }, {
    "id": 103,
    "name": "Noadkoko",
    "types": ["Plante", "Psy"],
    "hp": 95,
    "Attack": 95,
    "Defense": 85,
    "SpAttack": 125,
    "SpDefense": 75,
    "Vitesse": 55,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/103.png"
  }, {
    "id": 104,
    "name": "Osselait",
    "types": ["Sol"],
    "hp": 50,
    "Attack": 50,
    "Defense": 95,
    "SpAttack": 40,
    "SpDefense": 50,
    "Vitesse": 35,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/104.png"
  }, {
    "id": 105,
    "name": "Ossatueur",
    "types": ["Sol"],
    "hp": 60,
    "Attack": 80,
    "Defense": 110,
    "SpAttack": 50,
    "SpDefense": 80,
    "Vitesse": 45,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/105.png"
  }, {
    "id": 106,
    "name": "Kicklee",
    "types": ["Combat"],
    "hp": 50,
    "Attack": 120,
    "Defense": 53,
    "SpAttack": 35,
    "SpDefense": 110,
    "Vitesse": 87,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/106.png"
  }, {
    "id": 107,
    "name": "Tygnon",
    "types": ["Combat"],
    "hp": 50,
    "Attack": 105,
    "Defense": 79,
    "SpAttack": 35,
    "SpDefense": 110,
    "Vitesse": 76,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/107.png"
  }, {
    "id": 108,
    "name": "Excelangue",
    "types": ["Normal"],
    "hp": 90,
    "Attack": 55,
    "Defense": 75,
    "SpAttack": 60,
    "SpDefense": 75,
    "Vitesse": 30,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/108.png"
  }, {
    "id": 109,
    "name": "Smogo",
    "types": ["Poison"],
    "hp": 40,
    "Attack": 65,
    "Defense": 95,
    "SpAttack": 60,
    "SpDefense": 45,
    "Vitesse": 35,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/109.png"
  }, {
    "id": 110,
    "name": "Smogogo",
    "types": ["Poison"],
    "hp": 65,
    "Attack": 90,
    "Defense": 120,
    "SpAttack": 85,
    "SpDefense": 70,
    "Vitesse": 60,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/110.png"
  }, {
    "id": 111,
    "name": "Rhinocorne",
    "types": ["Sol", "Rock"],
    "hp": 80,
    "Attack": 85,
    "Defense": 95,
    "SpAttack": 30,
    "SpDefense": 30,
    "Vitesse": 25,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/111.png"
  }, {
    "id": 112,
    "name": "Rhinof\u00e9ros",
    "types": ["Sol", "Roche"],
    "hp": 105,
    "Attack": 130,
    "Defense": 120,
    "SpAttack": 45,
    "SpDefense": 45,
    "Vitesse": 40,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/112.png"
  }, {
    "id": 113,
    "name": "Leveinard",
    "types": ["Normal"],
    "hp": 250,
    "Attack": 5,
    "Defense": 5,
    "SpAttack": 35,
    "SpDefense": 105,
    "Vitesse": 50,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/113.png"
  }, {
    "id": 114,
    "name": "Saquedeneu",
    "types": ["Plante"],
    "hp": 65,
    "Attack": 55,
    "Defense": 115,
    "SpAttack": 100,
    "SpDefense": 40,
    "Vitesse": 60,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/114.png"
  }, {
    "id": 115,
    "name": "Kangourex",
    "types": ["Normal"],
    "hp": 105,
    "Attack": 95,
    "Defense": 80,
    "SpAttack": 40,
    "SpDefense": 80,
    "Vitesse": 90,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/115.png"
  }, {
    "id": 116,
    "name": "Hypotrempe",
    "types": ["Eau"],
    "hp": 30,
    "Attack": 40,
    "Defense": 70,
    "SpAttack": 70,
    "SpDefense": 25,
    "Vitesse": 60,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/116.png"
  }, {
    "id": 117,
    "name": "Hypocéan",
    "types": ["Eau"],
    "hp": 55,
    "Attack": 65,
    "Defense": 95,
    "SpAttack": 95,
    "SpDefense": 45,
    "Vitesse": 85,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/117.png"
  }, {
    "id": 118,
    "name": "Poissirène",
    "types": ["Eau"],
    "hp": 45,
    "Attack": 67,
    "Defense": 60,
    "SpAttack": 35,
    "SpDefense": 50,
    "Vitesse": 63,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/118.png"
  }, {
    "id": 119,
    "name": "Poissoroy",
    "types": ["Eau"],
    "hp": 80,
    "Attack": 92,
    "Defense": 65,
    "SpAttack": 65,
    "SpDefense": 80,
    "Vitesse": 68,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/119.png"
  }, {
    "id": 120,
    "name": "Stari",
    "types": ["Eau"],
    "hp": 30,
    "Attack": 45,
    "Defense": 55,
    "SpAttack": 70,
    "SpDefense": 55,
    "Vitesse": 85,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/120.png"
  }, {
    "id": 121,
    "name": "Staross",
    "types": ["Eau", "Psy"],
    "hp": 60,
    "Attack": 75,
    "Defense": 85,
    "SpAttack": 100,
    "SpDefense": 85,
    "Vitesse": 115,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/121.png"
  }, {
    "id": 122,
    "name": "M. Mime",
    "types": ["Psy", "Fée"],
    "hp": 40,
    "Attack": 45,
    "Defense": 65,
    "SpAttack": 100,
    "SpDefense": 120,
    "Vitesse": 90,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/122.png"
  }, {
    "id": 123,
    "name": "Insécateur",
    "types": ["Insecte", "Vol"],
    "hp": 70,
    "Attack": 110,
    "Defense": 80,
    "SpAttack": 55,
    "SpDefense": 80,
    "Vitesse": 105,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/123.png"
  }, {
    "id": 124,
    "name": "Lippoutou",
    "types": ["Glace", "Psy"],
    "hp": 65,
    "Attack": 50,
    "Defense": 35,
    "SpAttack": 115,
    "SpDefense": 95,
    "Vitesse": 95,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/124.png"
  }, {
    "id": 125,
    "name": "\u00c9lektek",
    "types": ["Electrik"],
    "hp": 65,
    "Attack": 83,
    "Defense": 57,
    "SpAttack": 95,
    "SpDefense": 85,
    "Vitesse": 105,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/125.png"
  }, {
    "id": 126,
    "name": "Magmar",
    "types": ["Feu"],
    "hp": 65,
    "Attack": 95,
    "Defense": 57,
    "SpAttack": 100,
    "SpDefense": 85,
    "Vitesse": 93,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/126.png"
  }, {
    "id": 127,
    "name": "Scarabrute",
    "types": ["Insecte"],
    "hp": 65,
    "Attack": 125,
    "Defense": 100,
    "SpAttack": 55,
    "SpDefense": 70,
    "Vitesse": 85,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/127.png"
  }, {
    "id": 128,
    "name": "Tauros",
    "types": ["Normal"],
    "hp": 75,
    "Attack": 100,
    "Defense": 95,
    "SpAttack": 40,
    "SpDefense": 70,
    "Vitesse": 110,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/128.png"
  }, {
    "id": 129,
    "name": "Magicarpe",
    "types": ["Eau"],
    "hp": 20,
    "Attack": 10,
    "Defense": 55,
    "SpAttack": 15,
    "SpDefense": 20,
    "Vitesse": 80,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/129.png"
  }, {
    "id": 130,
    "name": "L\u00e9viator",
    "types": ["Eau", "Vol"],
    "hp": 95,
    "Attack": 125,
    "Defense": 79,
    "SpAttack": 60,
    "SpDefense": 100,
    "Vitesse": 81,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/130.png"
  }, {
    "id": 131,
    "name": "Lokhlass",
    "types": ["Eau", "Glace"],
    "hp": 130,
    "Attack": 85,
    "Defense": 80,
    "SpAttack": 85,
    "SpDefense": 95,
    "Vitesse": 60,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/131.png"
  }, {
    "id": 132,
    "name": "M\u00e9tamorph",
    "types": ["Normal"],
    "hp": 48,
    "Attack": 48,
    "Defense": 48,
    "SpAttack": 48,
    "SpDefense": 48,
    "Vitesse": 48,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/132.png"
  }, {
    "id": 133,
    "name": "\u00c9voli",
    "types": ["Normal"],
    "hp": 55,
    "Attack": 55,
    "Defense": 50,
    "SpAttack": 45,
    "SpDefense": 65,
    "Vitesse": 55,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/133.png"
  }, {
    "id": 134,
    "name": "Aquali",
    "types": ["Eau"],
    "hp": 130,
    "Attack": 65,
    "Defense": 60,
    "SpAttack": 110,
    "SpDefense": 95,
    "Vitesse": 65,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/134.png"
  }, {
    "id": 135,
    "name": "Voltali",
    "types": ["Electrik"],
    "hp": 65,
    "Attack": 65,
    "Defense": 60,
    "SpAttack": 110,
    "SpDefense": 95,
    "Vitesse": 130,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/135.png"
  }, {
    "id": 136,
    "name": "Pyroli",
    "types": ["Feu"],
    "hp": 65,
    "Attack": 130,
    "Defense": 60,
    "SpAttack": 95,
    "SpDefense": 110,
    "Vitesse": 65,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/136.png"
  }, {
    "id": 137,
    "name": "Porygon",
    "types": ["Normal"],
    "hp": 65,
    "Attack": 60,
    "Defense": 70,
    "SpAttack": 85,
    "SpDefense": 75,
    "Vitesse": 40,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/137.png"
  }, {
    "id": 138,
    "name": "Amonita",
    "types": ["Roche", "Eau"],
    "hp": 35,
    "Attack": 40,
    "Defense": 100,
    "SpAttack": 90,
    "SpDefense": 55,
    "Vitesse": 35,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/138.png"
  }, {
    "id": 139,
    "name": "Amonistar",
    "types": ["Roche", "Eau"],
    "hp": 70,
    "Attack": 60,
    "Defense": 125,
    "SpAttack": 115,
    "SpDefense": 70,
    "Vitesse": 55,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/139.png"
  }, {
    "id": 140,
    "name": "Kabuto",
    "types": ["Roche", "Eau"],
    "hp": 30,
    "Attack": 80,
    "Defense": 90,
    "SpAttack": 55,
    "SpDefense": 45,
    "Vitesse": 55,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/140.png"
  }, {
    "id": 141,
    "name": "Kabutops",
    "types": ["Roche", "Eau"],
    "hp": 60,
    "Attack": 115,
    "Defense": 105,
    "SpAttack": 65,
    "SpDefense": 70,
    "Vitesse": 80,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/141.png"
  }, {
    "id": 142,
    "name": "Pt\u00e9ra",
    "types": ["Roche", "Vol"],
    "hp": 80,
    "Attack": 105,
    "Defense": 65,
    "SpAttack": 60,
    "SpDefense": 75,
    "Vitesse": 130,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/142.png"
  }, {
    "id": 143,
    "name": "Ronflex",
    "types": ["Normal"],
    "hp": 160,
    "Attack": 110,
    "Defense": 65,
    "SpAttack": 65,
    "SpDefense": 110,
    "Vitesse": 30,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/143.png"
  }, {
    "id": 144,
    "name": "Artikodin",
    "types": ["Glace", "Vol"],
    "hp": 90,
    "Attack": 85,
    "Defense": 100,
    "SpAttack": 95,
    "SpDefense": 125,
    "Vitesse": 85,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/144.png"
  }, {
    "id": 145,
    "name": "\u00c9lecthor",
    "types": ["Electrik", "Vol"],
    "hp": 90,
    "Attack": 90,
    "Defense": 85,
    "SpAttack": 125,
    "SpDefense": 90,
    "Vitesse": 100,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/145.png"
  }, {
    "id": 146,
    "name": "Sulfura",
    "types": ["Feu", "Vol"],
    "hp": 90,
    "Attack": 100,
    "Defense": 90,
    "SpAttack": 125,
    "SpDefense": 85,
    "Vitesse": 90,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/146.png"
  }, {
    "id": 147,
    "name": "Minidraco",
    "types": ["Dragon"],
    "hp": 41,
    "Attack": 64,
    "Defense": 45,
    "SpAttack": 50,
    "SpDefense": 50,
    "Vitesse": 50,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/147.png"
  }, {
    "id": 148,
    "name": "Draco",
    "types": ["Dragon"],
    "hp": 61,
    "Attack": 84,
    "Defense": 65,
    "SpAttack": 70,
    "SpDefense": 70,
    "Vitesse": 70,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/148.png"
  }, {
    "id": 149,
    "name": "Dracolosse",
    "types": ["Dragon", "Vol"],
    "hp": 91,
    "Attack": 134,
    "Defense": 95,
    "SpAttack": 100,
    "SpDefense": 100,
    "Vitesse": 80,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/149.png"
  }, {
    "id": 150,
    "name": "Mewtwo",
    "types": ["Psy"],
    "hp": 106,
    "Attack": 110,
    "Defense": 90,
    "SpAttack": 154,
    "SpDefense": 90,
    "Vitesse": 130,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/150.png"
  }, {
    "id": 151,
    "name": "Mew",
    "types": ["Psy"],
    "hp": 100,
    "Attack": 100,
    "Defense": 100,
    "SpAttack": 100,
    "SpDefense": 100,
    "Vitesse": 100,
    "created": new Date(),
    "picture": "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/151.png"
  },
];
